version: '2'
services:
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "9000:9000"
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"
      - "8020:8020"
      - "9870:9870"
      - "8088:8088"
      - "18080:18080"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      
  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "8042:8042"
      - "50475:50475"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  # spark-worker-2:
  #   image: bde2020/spark-worker:2.4.5-hadoop2.7
  #   container_name: spark-worker-2
  #   hostname: spark-worker-2
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "8082:8081"
  #     - "8043:8042"
  #     - "50476:50475"
  #   environment:
  #     - "SPARK_MASTER=spark://spark-master:7077"
